compress:
	gifsicle --resize 750x300 --colors 16 gaussian_ppi.gif > gaussian_ppi_smaller.gif
	gifsicle --resize 900x300 --colors 16 iw_ppi.gif > iw_ppi_smaller.gif
	gifsicle --resize 900x300 --colors 16 se_policy_timeshift.gif > se_policy_timeshift_smaller.gif
	gifsicle --resize 900x300 --colors 16 wn_policy_timeshift.gif > wn_policy_timeshift_smaller.gif
	gifsicle --resize 900x300 --colors 16 rff_policy_timeshift.gif > rff_policy_timeshift_smaller.gif
	gifsicle --resize 900x300 --colors 16 rbf_policy_timeshift.gif > rbf_policy_timeshift_smaller.gif
	gifsicle --resize 900x300 --colors 16 policy_time_resolution.gif > policy_time_resolution_smaller.gif
	convert ess_cem_nonlinear_ppi.png -resize 900x300 ess_cem_nonlinear_ppi_smaller.png
	convert lbps_nonlinear_ppi.png -resize 900x300 lbps_nonlinear_ppi_smaller.png
